calculate_distribution – PIC-MPI
calculate_distribution Subroutine
14 statements
Source File
public pure subroutine calculate_distribution(ncols, nranks, rank, first_col, my_ncols)
Calculate column distribution for a rank
Distributes ncols columns across nranks as evenly as possible. Extra columns go to lower-numbered ranks.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: ncols
Total number of columns
integer(kind=int32), intent(in) :: nranks
Total number of columns Number of MPI ranks
integer(kind=int32), intent(in) :: rank
Total number of columns Number of MPI ranks This rank’s number (0-indexed)
integer(kind=int32), intent(out) :: first_col
Output: first column owned (0-indexed)
integer(kind=int32), intent(out) :: my_ncols
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: base_cols
integer(kind=int32), private :: extra
Source Code
   pure subroutine calculate_distribution(ncols, nranks, rank, first_col, my_ncols)
      integer(int32), intent(in) :: ncols, nranks, rank
      integer(int32), intent(out) :: first_col, my_ncols
      integer(int32) :: base_cols, extra
      base_cols = ncols/nranks
      extra = mod(ncols, nranks)
      ! Ranks 0..extra-1 get one extra column
      if (rank < extra) then
         my_ncols = base_cols + 1
         first_col = rank*(base_cols + 1)
      else
         my_ncols = base_cols
         first_col = extra*(base_cols + 1) + (rank - extra)*base_cols
      end if
   end subroutine calculate_distribution
Call graph
darray_create_dp calls calculate_distribution
darray_create_i32 calls calculate_distribution
darray_create_i64 calls calculate_distribution
darray_create_sp calls calculate_distribution
darray_distrib calls calculate_distribution
get_local_offset calls calculate_distribution
darray_create calls darray_create_dp, darray_create_i32, darray_create_i64, darray_create_sp
darray_acc_dp calls get_local_offset
darray_acc_i32 calls get_local_offset
darray_acc_i64 calls get_local_offset
darray_acc_sp calls get_local_offset
darray_get_dp calls get_local_offset
darray_get_i32 calls get_local_offset
darray_get_i64 calls get_local_offset
darray_get_sp calls get_local_offset
darray_put_dp calls get_local_offset
darray_put_i32 calls get_local_offset
darray_put_i64 calls get_local_offset
darray_put_sp calls get_local_offset
darray_acc calls darray_acc_dp, darray_acc_i32, darray_acc_i64, darray_acc_sp
darray_get calls darray_get_dp, darray_get_i32, darray_get_i64, darray_get_sp
darray_put calls darray_put_dp, darray_put_i32, darray_put_i64, darray_put_sp