comm_recv_real_dp – PIC-MPI
comm_recv_real_dp Subroutine
15 statements
Source File
private subroutine comm_recv_real_dp(comm, data, source, tag, status)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out), optional :: status
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: ierr
integer, private :: stat(MPI_STATUS_SIZE)
Source Code
   subroutine comm_recv_real_dp(comm, data, source, tag, status)
      type(comm_t), intent(in) :: comm
      real(dp), intent(out) :: data
      integer(int32), intent(in) :: source
      integer(int32), intent(in) :: tag
      integer(int32) :: ierr
      type(MPI_Status), intent(out), optional :: status
      integer :: stat(MPI_STATUS_SIZE)
      if (present(status)) then
         call MPI_Recv(data, 1, MPI_DOUBLE_PRECISION, source, tag, comm%m_comm, stat, ierr)
         status = status_array_to_type(stat)
      else
         call MPI_Recv(data, 1, MPI_DOUBLE_PRECISION, source, tag, comm%m_comm, stat, ierr)
      end if
   end subroutine comm_recv_real_dp
Call graph
comm_recv_real_dp calls mpi_recv, status_array_to_type
recv calls comm_recv_real_dp