comm_duplicate – PIC-MPI
comm_duplicate Function
12 statements
Source File
private function comm_duplicate(this) result(new_comm)
Type Bound
comm_t
Arguments
Type Intent Optional Attributes Name
class(comm_t), intent(in) :: this
Return Value type(comm_t)
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: ierr
type(MPI_Comm), private :: mpi_comm_new
Source Code
   function comm_duplicate(this) result(new_comm)
      class(comm_t), intent(in) :: this
      type(comm_t) :: new_comm
      type(MPI_Comm) :: mpi_comm_new
      integer(int32) :: ierr
      if (.not. this%is_valid) then
         new_comm = comm_null()
         return
      end if
      call MPI_Comm_dup(this%m_comm, mpi_comm_new, ierr)
      new_comm = create_comm_from_mpi(mpi_comm_new)
   end function comm_duplicate
Call graph
comm_duplicate calls comm_null, mpi_comm_dup, create_comm_from_mpi
comm_null calls create_null_comm
create_comm_from_mpi calls mpi_comm_rank, mpi_comm_size