comm_discard_to – PIC-MPI
comm_discard_to Function
16 statements
Source File
private function comm_discard_to(this, num_ranks) result(new_comm)
Type Bound
comm_t
Arguments
Type Intent Optional Attributes Name
class(comm_t), intent(in) :: this
integer, intent(in) :: num_ranks
Return Value type(comm_t)
Calls
Variables
Type Visibility Attributes Name Initial
integer, private :: color
Source Code
   function comm_discard_to(this, num_ranks) result(new_comm)
      class(comm_t), intent(in) :: this
      integer, intent(in) :: num_ranks
      type(comm_t) :: new_comm
      integer :: color
      if (.not. this%is_valid) then
         new_comm = comm_null()
         return
      end if
      if (this%rank() < num_ranks) then
         color = 0
      else
         color = MPI_UNDEFINED
      end if
      new_comm = this%split_by(color)
   end function comm_discard_to
Call graph
comm_discard_to calls comm_null, comm_split_by_color
comm_null calls create_null_comm
comm_split_by_color calls comm_null, mpi_comm_split, create_comm_from_mpi
create_comm_from_mpi calls mpi_comm_rank, mpi_comm_size