comm_barrier – PIC-MPI
comm_barrier Subroutine
5 statements
Source File
private subroutine comm_barrier(this)
Blocks until all processes in the communicator have called barrier
Type Bound
comm_t
Arguments
Type Intent Optional Attributes Name
class(comm_t), intent(in) :: this
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: ierr
Source Code
   subroutine comm_barrier(this)
   !! Blocks until all processes in the communicator have called barrier
      class(comm_t), intent(in) :: this
      integer(int32) :: ierr
      call MPI_Barrier(this%m_comm, ierr)
   end subroutine comm_barrier
Call graph
comm_barrier calls mpi_barrier
darray_create_dp calls comm_barrier
darray_create_i32 calls comm_barrier
darray_create_i64 calls comm_barrier
darray_create_sp calls comm_barrier
darray_destroy calls comm_barrier
darray_sync calls comm_barrier
dlb_finalize calls comm_barrier
dlb_init calls comm_barrier
darray_create calls darray_create_dp, darray_create_i32, darray_create_i64, darray_create_sp
darrays_finalize calls darray_destroy