comm_get – PIC-MPI
comm_get Function
8 statements
Source File
private function comm_get(this) result(mpi_comm_out)
Type Bound
comm_t
Arguments
Type Intent Optional Attributes Name
class(comm_t), intent(in) :: this
Return Value type(MPI_Comm)
Called by
Source Code
   function comm_get(this) result(mpi_comm_out)
      class(comm_t), intent(in) :: this
      type(MPI_Comm) :: mpi_comm_out
      if (.not. this%is_valid) then
         error stop "Cannot get MPI_Comm from null Comm"
      end if
      mpi_comm_out = this%m_comm
   end function comm_get
Call graph
allreduce_dp_array_to calls comm_get
allreduce_dp_array calls comm_get
allreduce_dp_to calls comm_get
allreduce_dp calls comm_get
allreduce_i32_array calls comm_get
allreduce_i32 calls comm_get
allreduce_sp_array_to calls comm_get
allreduce_sp_array calls comm_get
allreduce_sp_to calls comm_get
allreduce_sp calls comm_get
comm_split_shared calls comm_get
create_win_allocate_dp_1d calls comm_get
create_win_allocate_dp_2d calls comm_get
create_win_allocate_i32_1d calls comm_get
create_win_allocate_i64_1d calls comm_get
create_win_allocate_sp_1d calls comm_get
create_win_dp_array calls comm_get
create_win_dynamic calls comm_get
allreduce calls allreduce_dp_array_to, allreduce_dp_array, allreduce_dp_to, allreduce_dp, allreduce_i32_array, allreduce_i32, allreduce_sp_array_to, allreduce_sp_array, allreduce_sp_to, allreduce_sp
win_allocate calls create_win_allocate_dp_1d, create_win_allocate_dp_2d, create_win_allocate_i32_1d, create_win_allocate_i64_1d, create_win_allocate_sp_1d
win_create_dynamic calls create_win_dynamic
win_create calls create_win_dp_array
darray_create_dp calls win_allocate
darray_create_i32 calls win_allocate
darray_create_i64 calls win_allocate
darray_create_sp calls win_allocate
darray_gsumf calls allreduce
darray_gsumi calls allreduce
dlb_init calls win_allocate
darray_create calls darray_create_dp, darray_create_i32, darray_create_i64, darray_create_sp