create_win_allocate_i32_1d – PIC-MPI
create_win_allocate_i32_1d Subroutine
15 statements
Source File
private subroutine create_win_allocate_i32_1d(comm, length, baseptr, win)
Uses
iso_c_binding
Allocate window memory for int32 1D array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer, intent(in) :: length
integer(kind=int32), intent(out), pointer :: baseptr(:)
type(win_t), intent(out) :: win
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(c_ptr), private :: cptr
integer, private :: disp_unit
integer, private :: ierr
integer(kind=MPI_ADDRESS_KIND), private :: win_size
Source Code
   subroutine create_win_allocate_i32_1d(comm, length, baseptr, win)
      use iso_c_binding, only: c_ptr, c_f_pointer
      type(comm_t), intent(in) :: comm
      integer, intent(in) :: length
      integer(int32), pointer, intent(out) :: baseptr(:)
      type(win_t), intent(out) :: win
      type(c_ptr) :: cptr
      integer(MPI_ADDRESS_KIND) :: win_size
      integer :: disp_unit, ierr
      win_size = int(length, MPI_ADDRESS_KIND)*int(storage_size(1_int32)/8_int32, MPI_ADDRESS_KIND)
      disp_unit = int(storage_size(1_int32)/8_int32)
      call MPI_Win_allocate(win_size, disp_unit, MPI_INFO_NULL, &
                            comm%get(), cptr, win%m_win, ierr)
      call c_f_pointer(cptr, baseptr, [length])
      win%is_valid = .true.
   end subroutine create_win_allocate_i32_1d
Call graph
create_win_allocate_i32_1d calls mpi_win_allocate, comm_get
win_allocate calls create_win_allocate_i32_1d