create_comm_from_mpi – PIC-MPI
create_comm_from_mpi Function
13 statements
Source File
private function create_comm_from_mpi(mpi_comm_in) result(comm)
Internal helper function that wraps an MPI_Comm into a comm_t object and caches rank and size information
Arguments
Type Intent Optional Attributes Name
type(MPI_Comm), intent(in) :: mpi_comm_in
Return Value type(comm_t)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: ierr
Source Code
   function create_comm_from_mpi(mpi_comm_in) result(comm)
   !! Internal helper function that wraps an MPI_Comm into a comm_t object
   !! and caches rank and size information
      type(MPI_Comm), intent(in) :: mpi_comm_in
      type(comm_t) :: comm
      integer(int32) :: ierr
      comm%m_comm = mpi_comm_in
      if (mpi_comm_in /= MPI_COMM_NULL) then
         call MPI_Comm_rank(comm%m_comm, comm%m_rank, ierr)
         call MPI_Comm_size(comm%m_comm, comm%m_size, ierr)
         comm%is_valid = .true.
      else
         comm%is_valid = .false.
      end if
   end function create_comm_from_mpi
Call graph
create_comm_from_mpi calls mpi_comm_rank, mpi_comm_size
comm_duplicate calls create_comm_from_mpi
comm_split_by_color calls create_comm_from_mpi
comm_split_shared calls create_comm_from_mpi
create_world_comm calls create_comm_from_mpi
comm_world calls create_world_comm
comm_discard_leader calls comm_split_by_color
comm_discard_to calls comm_split_by_color
darrays_init calls comm_duplicate
darrays_set_comm calls comm_duplicate
dlb_init calls comm_duplicate