create_win_allocate_dp_1d – PIC-MPI
create_win_allocate_dp_1d Subroutine
15 statements
Source File
private subroutine create_win_allocate_dp_1d(comm, length, baseptr, win)
Uses
iso_c_binding
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(in) :: length
real(kind=dp), intent(out), pointer :: baseptr(:)
type(win_t), intent(out) :: win
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(c_ptr), private :: cptr
integer(kind=int32), private :: disp_unit
integer(kind=int32), private :: ierr
integer(kind=MPI_ADDRESS_KIND), private :: win_size
Source Code
   subroutine create_win_allocate_dp_1d(comm, length, baseptr, win)
      use iso_c_binding, only: c_ptr, c_f_pointer
      type(comm_t), intent(in) :: comm
      integer(int32), intent(in) :: length
      real(dp), pointer, intent(out) :: baseptr(:)
      type(win_t), intent(out) :: win
      type(c_ptr) :: cptr
      integer(MPI_ADDRESS_KIND) :: win_size
      integer(int32) :: disp_unit, ierr
      win_size = int(length, MPI_ADDRESS_KIND)*int(storage_size(1.0_dp)/8_int32, MPI_ADDRESS_KIND)
      disp_unit = int(storage_size(1.0_dp)/8_int32, int32)
      call MPI_Win_allocate(win_size, disp_unit, MPI_INFO_NULL, &
                            comm%get(), cptr, win%m_win, ierr)
      call c_f_pointer(cptr, baseptr, [length])
      win%is_valid = .true.
   end subroutine create_win_allocate_dp_1d
Call graph
create_win_allocate_dp_1d calls mpi_win_allocate, comm_get
win_allocate calls create_win_allocate_dp_1d
darray_create_dp calls win_allocate
darray_create_i32 calls win_allocate
darray_create_i64 calls win_allocate
darray_create_sp calls win_allocate
dlb_init calls win_allocate
darray_create calls darray_create_dp, darray_create_i32, darray_create_i64, darray_create_sp