create_world_comm – PIC-MPI
create_world_comm Function
7 statements
Source File
private function create_world_comm() result(comm)
Arguments
None
Return Value type(comm_t)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer, private :: dup_comm
integer(kind=int32), private :: ierr
Source Code
   function create_world_comm() result(comm)
      type(comm_t) :: comm
      integer :: dup_comm
      integer(int32) :: ierr
      call MPI_Comm_dup(MPI_COMM_WORLD, dup_comm, ierr)
      comm = create_comm_from_mpi(dup_comm)
   end function create_world_comm
Call graph
create_world_comm calls mpi_comm_dup, create_comm_from_mpi
create_comm_from_mpi calls mpi_comm_rank, mpi_comm_size
comm_world calls create_world_comm