create_null_comm – PIC-MPI
create_null_comm Function
7 statements
Source File
private function create_null_comm() result(comm)
Creates an invalid/null communicator object that can be used for initialization or to represent absence of a communicator.
Arguments
None
Return Value type(comm_t)
Called by
Source Code
   function create_null_comm() result(comm)
   !! Creates an invalid/null communicator object that can be used
   !! for initialization or to represent absence of a communicator.
      type(comm_t) :: comm
      ! Explicitly initialize to null/invalid state
      comm%m_comm = MPI_COMM_NULL
      comm%m_rank = -1
      comm%m_size = -1
      comm%is_valid = .false.
   end function create_null_comm
Call graph
comm_null calls create_null_comm
comm_discard_leader calls comm_null, comm_split_by_color
comm_discard_to calls comm_null, comm_split_by_color
comm_duplicate calls comm_null
comm_split_by_color calls comm_null
comm_split_shared calls comm_null