darrays_finalize – PIC-MPI
darrays_finalize Subroutine
11 statements
Source File
public subroutine darrays_finalize()
Finalize the distributed arrays module
Arguments
None
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: i
Source Code
   subroutine darrays_finalize()
      integer(int32) :: i
      if (.not. initialized) return
      do i = 1, MAX_ARRAYS
         if (registry(i)%active) then
            call darray_destroy(i)
         end if
      end do
      call global_comm%finalize()
      initialized = .false.
   end subroutine darrays_finalize
Call graph
darrays_finalize calls comm_finalize, darray_destroy
comm_finalize calls mpi_comm_free
darray_destroy calls comm_barrier, win_finalize
comm_barrier calls mpi_barrier
win_finalize calls mpi_win_free