darray_gsumf – PIC-MPI
darray_gsumf Subroutine
10 statements
Source File
public subroutine darray_gsumf(buffer, n)
Global sum for double precision array (DDI_GSUMF equivalent)
In-place reduction across all ranks.
Arguments
Type Intent Optional Attributes Name
real(kind=dp), intent(inout) :: buffer(*)
integer(kind=int32), intent(in) :: n
Calls
Variables
Type Visibility Attributes Name Initial
real(kind=dp), private, allocatable :: temp(:)
Source Code
   subroutine darray_gsumf(buffer, n)
      real(dp), intent(inout) :: buffer(*)
      integer(int32), intent(in) :: n
      real(dp), allocatable :: temp(:)
      allocate (temp(n))
      temp = buffer(1:n)
      call allreduce(wrapper_comm, temp, n)
      buffer(1:n) = temp
      deallocate (temp)
   end subroutine darray_gsumf
Call graph
darray_gsumf calls allreduce
allreduce calls allreduce_dp_array_to, allreduce_dp_array, allreduce_dp_to, allreduce_dp, allreduce_i32_array, allreduce_i32, allreduce_sp_array_to, allreduce_sp_array, allreduce_sp_to, allreduce_sp
allreduce_dp_array_to calls mpi_allreduce, comm_get
allreduce_dp_array calls mpi_allreduce, comm_get
allreduce_dp_to calls mpi_allreduce, comm_get
allreduce_dp calls mpi_allreduce, comm_get
allreduce_i32_array calls mpi_allreduce, comm_get
allreduce_i32 calls mpi_allreduce, comm_get
allreduce_sp_array_to calls mpi_allreduce, comm_get
allreduce_sp_array calls mpi_allreduce, comm_get
allreduce_sp_to calls mpi_allreduce, comm_get
allreduce_sp calls mpi_allreduce, comm_get