darray_create_i32 – PIC-MPI
darray_create_i32 Subroutine
25 statements
Source File
private subroutine darray_create_i32(nrows, ncols, handle, init_val)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: nrows
integer(kind=int32), intent(in) :: ncols
integer(kind=int32), intent(out) :: handle
integer(kind=int32), intent(in) :: init_val
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(darray_t), private, pointer :: arr
integer(kind=int32), private :: length
integer(kind=int32), private :: slot
Source Code
   subroutine darray_create_i32(nrows, ncols, handle, init_val)
      integer(int32), intent(in) :: nrows, ncols
      integer(int32), intent(out) :: handle
      integer(int32), intent(in) :: init_val
      type(darray_t), pointer :: arr
      integer(int32) :: slot, length
      slot = find_free_slot()
      arr => registry(slot)
      arr%handle = slot
      arr%dtype = DTYPE_I32
      arr%nrows = nrows
      arr%ncols = ncols
      call calculate_distribution(ncols, global_comm%size(), global_comm%rank(), &
                                  arr%my_first_col, arr%my_ncols)
      arr%local_size = int(nrows, int64)*int(arr%my_ncols, int64)
      length = int(arr%local_size, int32)
      if (length > 0) then
         call win_allocate(global_comm, length, arr%data_i32, arr%win)
      else
         call win_allocate(global_comm, 1_int32, arr%data_i32, arr%win)
      end if
      arr%data_i32 = init_val
      arr%active = .true.
      handle = slot
      call global_comm%barrier()
   end subroutine darray_create_i32
Call graph
darray_create_i32 calls win_allocate, calculate_distribution, comm_barrier, find_free_slot
win_allocate calls create_win_allocate_dp_1d, create_win_allocate_dp_2d, create_win_allocate_i32_1d, create_win_allocate_i64_1d, create_win_allocate_sp_1d
comm_barrier calls mpi_barrier
create_win_allocate_dp_1d calls mpi_win_allocate, comm_get
create_win_allocate_dp_2d calls mpi_win_allocate, comm_get
create_win_allocate_i32_1d calls mpi_win_allocate, comm_get
create_win_allocate_i64_1d calls mpi_win_allocate, comm_get
create_win_allocate_sp_1d calls mpi_win_allocate, comm_get
darray_create calls darray_create_i32