darray_acc_i64 – PIC-MPI
darray_acc_i64 Subroutine
19 statements
Source File
private subroutine darray_acc_i64(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
integer(kind=int64), intent(in) :: buffer(*)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
type(darray_t), private, pointer :: arr
integer(kind=int32), private :: buf_offset
integer(kind=int32), private :: col
integer(kind=MPI_ADDRESS_KIND), private :: disp
integer(kind=int32), private :: j
integer(kind=int32), private :: nranks
integer(kind=int32), private :: nrows_patch
integer(kind=int32), private :: owner
Source Code
   subroutine darray_acc_i64(handle, ilo, ihi, jlo, jhi, buffer)
      integer(int32), intent(in) :: handle, ilo, ihi, jlo, jhi
      integer(int64), intent(in) :: buffer(*)
      type(darray_t), pointer :: arr
      integer(MPI_ADDRESS_KIND) :: disp
      integer(int32) :: j, col, owner, nrows_patch, buf_offset, nranks
      arr => registry(handle)
      nrows_patch = ihi - ilo + 1
      nranks = global_comm%size()
      do j = jlo, jhi
         col = j - 1
         owner = get_owner(arr%ncols, nranks, col)
         disp = get_local_offset(arr%nrows, arr%ncols, nranks, ilo - 1, col)
         buf_offset = (j - jlo)*nrows_patch + 1
         call arr%win%lock(owner)
         call arr%win%accumulate_i64(owner, disp, nrows_patch, buffer(buf_offset))
         call arr%win%unlock(owner)
      end do
   end subroutine darray_acc_i64
Call graph
darray_acc_i64 calls get_local_offset, get_owner, win_accumulate_i64
get_local_offset calls get_owner, calculate_distribution
win_accumulate_i64 calls mpi_accumulate
darray_acc calls darray_acc_i64