darrays_init – PIC-MPI
darrays_init Subroutine
10 statements
Source File
public subroutine darrays_init(comm)
Initialize the distributed arrays module
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: i
Source Code
   subroutine darrays_init(comm)
      type(comm_t), intent(in) :: comm
      integer(int32) :: i
      global_comm = comm%duplicate()
      do i = 1, MAX_ARRAYS
         registry(i)%active = .false.
         registry(i)%handle = -1
      end do
      initialized = .true.
   end subroutine darrays_init
Call graph
darrays_init calls comm_duplicate
comm_duplicate calls comm_null, mpi_comm_dup, create_comm_from_mpi
comm_null calls create_null_comm
create_comm_from_mpi calls mpi_comm_rank, mpi_comm_size