darray_gsumi – PIC-MPI
darray_gsumi Subroutine
10 statements
Source File
public subroutine darray_gsumi(buffer, n)
Global sum for integer array (DDI_GSUMI equivalent)
In-place reduction across all ranks.
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(inout) :: buffer(*)
integer(kind=int32), intent(in) :: n
Calls
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private, allocatable :: temp(:)
Source Code
   subroutine darray_gsumi(buffer, n)
      integer(int32), intent(inout) :: buffer(*)
      integer(int32), intent(in) :: n
      integer(int32), allocatable :: temp(:)
      allocate (temp(n))
      temp = buffer(1:n)
      call allreduce(wrapper_comm, temp, n)
      buffer(1:n) = temp
      deallocate (temp)
   end subroutine darray_gsumi
Call graph
darray_gsumi calls allreduce
allreduce calls allreduce_dp_array_to, allreduce_dp_array, allreduce_dp_to, allreduce_dp, allreduce_i32_array, allreduce_i32, allreduce_sp_array_to, allreduce_sp_array, allreduce_sp_to, allreduce_sp
allreduce_dp_array_to calls mpi_allreduce, comm_get
allreduce_dp_array calls mpi_allreduce, comm_get
allreduce_dp_to calls mpi_allreduce, comm_get
allreduce_dp calls mpi_allreduce, comm_get
allreduce_i32_array calls mpi_allreduce, comm_get
allreduce_i32 calls mpi_allreduce, comm_get
allreduce_sp_array_to calls mpi_allreduce, comm_get
allreduce_sp_array calls mpi_allreduce, comm_get
allreduce_sp_to calls mpi_allreduce, comm_get
allreduce_sp calls mpi_allreduce, comm_get