dlb_init – PIC-MPI
dlb_init Subroutine
8 statements
Source File
public subroutine dlb_init(comm)
Initialize dynamic load balancing
Creates a shared counter window on rank 0.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
MPI communicator to use
Calls
Source Code
   subroutine dlb_init(comm)
      type(comm_t), intent(in) :: comm
      dlb_comm = comm%duplicate()
      ! Allocate counter on all ranks (rank 0's is the master)
      call win_allocate(dlb_comm, 1_int32, counter_ptr, counter_win)
      counter_ptr(1) = 0_int64
      call dlb_comm%barrier()
      dlb_initialized = .true.
   end subroutine dlb_init
Call graph
dlb_init calls win_allocate, comm_barrier, comm_duplicate
win_allocate calls create_win_allocate_dp_1d, create_win_allocate_dp_2d, create_win_allocate_i32_1d, create_win_allocate_i64_1d, create_win_allocate_sp_1d
comm_barrier calls mpi_barrier
comm_duplicate calls comm_null, mpi_comm_dup, create_comm_from_mpi
comm_null calls create_null_comm
create_comm_from_mpi calls mpi_comm_rank, mpi_comm_size
create_win_allocate_dp_1d calls mpi_win_allocate, comm_get
create_win_allocate_dp_2d calls mpi_win_allocate, comm_get
create_win_allocate_i32_1d calls mpi_win_allocate, comm_get
create_win_allocate_i64_1d calls mpi_win_allocate, comm_get
create_win_allocate_sp_1d calls mpi_win_allocate, comm_get