find_free_slot – PIC-MPI
find_free_slot Function
14 statements
Source File
private function find_free_slot() result(slot)
Find a free registry slot
Arguments
None
Return Value integer(kind=int32)
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: i
Source Code
   function find_free_slot() result(slot)
      integer(int32) :: slot
      integer(int32) :: i
      slot = -1
      do i = 1, MAX_ARRAYS
         if (.not. registry(i)%active) then
            slot = i
            exit
         end if
      end do
      if (slot < 0) then
         error stop "darrays: no free registry slots"
      end if
   end function find_free_slot
Call graph
darray_create_dp calls find_free_slot
darray_create_i32 calls find_free_slot
darray_create_i64 calls find_free_slot
darray_create_sp calls find_free_slot
darray_create calls darray_create_dp, darray_create_i32, darray_create_i64, darray_create_sp