get_owner – PIC-MPI
get_owner Function
13 statements
Source File
public pure function get_owner(ncols, nranks, col) result(owner)
Find which rank owns a given column
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: ncols
Total number of columns
integer(kind=int32), intent(in) :: nranks
Total number of columns Number of MPI ranks
integer(kind=int32), intent(in) :: col
Total number of columns Number of MPI ranks Column index (0-indexed)
Return Value integer(kind=int32)
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: base_cols
integer(kind=int32), private :: boundary
integer(kind=int32), private :: extra
Source Code
   pure function get_owner(ncols, nranks, col) result(owner)
      integer(int32), intent(in) :: ncols, nranks, col
      integer(int32) :: owner
      integer(int32) :: base_cols, extra, boundary
      base_cols = ncols/nranks
      extra = mod(ncols, nranks)
      ! Boundary where ranks switch from (base+1) to base columns
      boundary = extra*(base_cols + 1)
      if (col < boundary) then
         owner = col/(base_cols + 1)
      else
         owner = extra + (col - boundary)/base_cols
      end if
   end function get_owner
Call graph
darray_acc_dp calls get_owner, get_local_offset
darray_acc_i32 calls get_owner, get_local_offset
darray_acc_i64 calls get_owner, get_local_offset
darray_acc_sp calls get_owner, get_local_offset
darray_get_dp calls get_owner, get_local_offset
darray_get_i32 calls get_owner, get_local_offset
darray_get_i64 calls get_owner, get_local_offset
darray_get_sp calls get_owner, get_local_offset
darray_put_dp calls get_owner, get_local_offset
darray_put_i32 calls get_owner, get_local_offset
darray_put_i64 calls get_owner, get_local_offset
darray_put_sp calls get_owner, get_local_offset
get_local_offset calls get_owner
darray_acc calls darray_acc_dp, darray_acc_i32, darray_acc_i64, darray_acc_sp
darray_get calls darray_get_dp, darray_get_i32, darray_get_i64, darray_get_sp
darray_put calls darray_put_dp, darray_put_i32, darray_put_i64, darray_put_sp