get_local_offset – PIC-MPI
get_local_offset Function
8 statements
Source File
public pure function get_local_offset(nrows, ncols, nranks, row, col) result(offset)
Get local offset in owner’s window for a given (row, col)
Returns the displacement in the owner’s local_data array for the element at (row, col) in the global array. Data is stored column-major: offset = row + (local_col * nrows)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: nrows
Number of rows in array
integer(kind=int32), intent(in) :: ncols
Number of rows in array Number of columns in array
integer(kind=int32), intent(in) :: nranks
Number of rows in array Number of columns in array Number of MPI ranks
integer(kind=int32), intent(in) :: row
Number of rows in array Number of columns in array Number of MPI ranks Row index (0-indexed)
integer(kind=int32), intent(in) :: col
Number of rows in array Number of columns in array Number of MPI ranks Row index (0-indexed) Column index (0-indexed)
Return Value integer(kind=MPI_ADDRESS_KIND)
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: local_col
integer(kind=int32), private :: owner_first_col
integer(kind=int32), private :: owner_ncols
Source Code
   pure function get_local_offset(nrows, ncols, nranks, row, col) result(offset)
      integer(int32), intent(in) :: nrows, ncols, nranks, row, col
      integer(MPI_ADDRESS_KIND) :: offset
      integer(int32) :: owner_first_col, owner_ncols, local_col
      call calculate_distribution(ncols, nranks, get_owner(ncols, nranks, col), &
                                  owner_first_col, owner_ncols)
      local_col = col - owner_first_col
      offset = int(row, MPI_ADDRESS_KIND) + int(local_col, MPI_ADDRESS_KIND)*int(nrows, MPI_ADDRESS_KIND)
   end function get_local_offset
Call graph
get_local_offset calls calculate_distribution, get_owner
darray_acc_dp calls get_local_offset
darray_acc_i32 calls get_local_offset
darray_acc_i64 calls get_local_offset
darray_acc_sp calls get_local_offset
darray_get_dp calls get_local_offset
darray_get_i32 calls get_local_offset
darray_get_i64 calls get_local_offset
darray_get_sp calls get_local_offset
darray_put_dp calls get_local_offset
darray_put_i32 calls get_local_offset
darray_put_i64 calls get_local_offset
darray_put_sp calls get_local_offset
darray_acc calls darray_acc_dp, darray_acc_i32, darray_acc_i64, darray_acc_sp
darray_get calls darray_get_dp, darray_get_i32, darray_get_i64, darray_get_sp
darray_put calls darray_put_dp, darray_put_i32, darray_put_i64, darray_put_sp