request_wait – PIC-MPI
request_wait Subroutine
14 statements
Source File
private subroutine request_wait(request, status)
Arguments
Type Intent Optional Attributes Name
type(request_t), intent(inout) :: request
type(MPI_Status), intent(out), optional :: status
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: ierr
integer, private :: stat(MPI_STATUS_SIZE)
Source Code
   subroutine request_wait(request, status)
      type(request_t), intent(inout) :: request
      type(MPI_Status), intent(out), optional :: status
      integer(int32) :: ierr
      integer :: stat(MPI_STATUS_SIZE)
      if (.not. request%is_valid) then
         error stop "Cannot wait on null request"
      end if
      call MPI_Wait(request%m_request, stat, ierr)
      if (present(status)) then
         status = status_array_to_type(stat)
      end if
      call request%free()
   end subroutine request_wait
Call graph
request_wait calls mpi_wait, status_array_to_type
wait calls request_wait