status_array_to_type – PIC-MPI
status_array_to_type Function
8 statements
Source File
private pure function status_array_to_type(status_array) result(status_type)
Convert legacy integer array status to MPI_Status type
Internal helper function for converting between array and type representations
Arguments
Type Intent Optional Attributes Name
integer, intent(in) :: status_array(MPI_STATUS_SIZE)
Return Value type(MPI_Status)
Called by
Source Code
   pure function status_array_to_type(status_array) result(status_type)
   !! Convert legacy integer array status to MPI_Status type
   !!
   !! Internal helper function for converting between array and type representations
      integer, intent(in) :: status_array(MPI_STATUS_SIZE)
      type(MPI_Status) :: status_type
      status_type%MPI_SOURCE = status_array(1)  ! MPI_SOURCE is at index 1
      status_type%MPI_TAG = status_array(2)     ! MPI_TAG is at index 2
      status_type%MPI_ERROR = status_array(3)   ! MPI_ERROR is at index 3
      status_type%internal(1:3) = status_array(4:6)
   end function status_array_to_type
Call graph
comm_iprobe calls status_array_to_type
comm_recv_integer calls status_array_to_type
comm_recv_integer64 calls status_array_to_type
comm_recv_integer64_array calls status_array_to_type
comm_recv_integer_array calls status_array_to_type
comm_recv_logical calls status_array_to_type
comm_recv_real_dp calls status_array_to_type
comm_recv_real_dp_array calls status_array_to_type
comm_recv_real_dp_array_2d calls status_array_to_type
comm_recv_real_sp calls status_array_to_type
comm_recv_real_sp_array calls status_array_to_type
comm_recv_real_sp_array_2d calls status_array_to_type
request_test calls status_array_to_type
request_wait calls status_array_to_type
request_waitall calls status_array_to_type
iprobe calls comm_iprobe
recv calls comm_recv_integer, comm_recv_integer64, comm_recv_integer64_array, comm_recv_integer_array, comm_recv_logical, comm_recv_real_dp, comm_recv_real_dp_array, comm_recv_real_dp_array_2d, comm_recv_real_sp, comm_recv_real_sp_array, comm_recv_real_sp_array_2d
test calls request_test
wait calls request_wait
waitall calls request_waitall