win_unlock_all – PIC-MPI
win_unlock_all Subroutine
5 statements
Source File
private subroutine win_unlock_all(this)
Type Bound
win_t
Arguments
Type Intent Optional Attributes Name
class(win_t), intent(in) :: this
Calls
Called by
Variables
Type Visibility Attributes Name Initial
integer(kind=int32), private :: ierr
Source Code
   subroutine win_unlock_all(this)
      class(win_t), intent(in) :: this
      integer(int32) :: ierr
      call MPI_Win_unlock_all(this%m_win, ierr)
   end subroutine win_unlock_all
Call graph
win_unlock_all calls mpi_win_unlock_all
darray_get_dp calls win_unlock_all
darray_get_i32 calls win_unlock_all
darray_get_i64 calls win_unlock_all
darray_get_sp calls win_unlock_all
darray_put_dp calls win_unlock_all
darray_put_i32 calls win_unlock_all
darray_put_i64 calls win_unlock_all
darray_put_sp calls win_unlock_all
darray_get calls darray_get_dp, darray_get_i32, darray_get_i64, darray_get_sp
darray_put calls darray_put_dp, darray_put_i32, darray_put_i64, darray_put_sp