allreduce – PIC-MPI
allreduce Interface
6 statements
Source File
public interface allreduce
Calls
Called by
Module Procedures
private subroutine allreduce_dp(comm, buffer, op)
Allreduce for scalar double precision
Read more…
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(inout) :: buffer
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_dp_array(comm, buffer, count, op)
Allreduce for double precision array
Read more…
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(inout) :: buffer(:)
integer, intent(in), optional :: count
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_i32(comm, buffer, op)
Allreduce for scalar integer
Read more…
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(inout) :: buffer
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_i32_array(comm, buffer, count, op)
Allreduce for integer array
Read more…
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(inout) :: buffer(:)
integer, intent(in), optional :: count
type(MPI_Op), intent(in), optional :: op
Call graph
allreduce calls allreduce_dp, allreduce_dp_array, allreduce_i32, allreduce_i32_array
allreduce_dp calls mpi_allreduce, comm_get
allreduce_dp_array calls mpi_allreduce, comm_get
allreduce_i32 calls mpi_allreduce, comm_get
allreduce_i32_array calls mpi_allreduce, comm_get
darray_gsumf calls allreduce
darray_gsumi calls allreduce