allreduce – PIC-MPI
allreduce Interface
12 statements
Source File
public interface allreduce
Calls
Called by
Module Procedures
private subroutine allreduce_dp(comm, buffer, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(inout) :: buffer
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_dp_array(comm, buffer, count, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(inout) :: buffer(:)
integer, intent(in), optional :: count
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_sp(comm, buffer, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(inout) :: buffer
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_sp_array(comm, buffer, count, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(inout) :: buffer(:)
integer, intent(in), optional :: count
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_i32(comm, buffer, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(inout) :: buffer
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_i32_array(comm, buffer, count, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(inout) :: buffer(:)
integer, intent(in), optional :: count
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_dp_to(comm, sendbuf, recvbuf, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(in) :: sendbuf
real(kind=dp), intent(out) :: recvbuf
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_dp_array_to(comm, sendbuf, recvbuf, count, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(in) :: sendbuf(:)
real(kind=dp), intent(out) :: recvbuf(:)
integer, intent(in), optional :: count
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_sp_to(comm, sendbuf, recvbuf, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(in) :: sendbuf
real(kind=sp), intent(out) :: recvbuf
type(MPI_Op), intent(in), optional :: op
private subroutine allreduce_sp_array_to(comm, sendbuf, recvbuf, count, op)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(in) :: sendbuf(:)
real(kind=sp), intent(out) :: recvbuf(:)
integer, intent(in), optional :: count
type(MPI_Op), intent(in), optional :: op
Call graph
allreduce calls allreduce_dp_array_to, allreduce_dp_array, allreduce_dp_to, allreduce_dp, allreduce_i32_array, allreduce_i32, allreduce_sp_array_to, allreduce_sp_array, allreduce_sp_to, allreduce_sp
allreduce_dp_array_to calls mpi_allreduce, comm_get
allreduce_dp_array calls mpi_allreduce, comm_get
allreduce_dp_to calls mpi_allreduce, comm_get
allreduce_dp calls mpi_allreduce, comm_get
allreduce_i32_array calls mpi_allreduce, comm_get
allreduce_i32 calls mpi_allreduce, comm_get
allreduce_sp_array_to calls mpi_allreduce, comm_get
allreduce_sp_array calls mpi_allreduce, comm_get
allreduce_sp_to calls mpi_allreduce, comm_get
allreduce_sp calls mpi_allreduce, comm_get
darray_gsumf calls allreduce
darray_gsumi calls allreduce