bcast – PIC-MPI
bcast Interface
8 statements
Source File
public interface bcast
Calls
Module Procedures
private subroutine comm_bcast_integer(comm, buffer, count, root)
Broadcasts integer data from root process to all processes in communicator
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(inout) :: buffer
integer(kind=int32), intent(in) :: count
integer(kind=int32), intent(in) :: root
private subroutine comm_bcast_integer64(comm, buffer, count, root)
Broadcasts integer64 data from root process to all processes in communicator
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(inout) :: buffer
integer(kind=int32), intent(in) :: count
integer(kind=int32), intent(in) :: root
private subroutine comm_bcast_real_dp(comm, buffer, count, root)
Broadcasts double precision data from root process to all processes in communicator
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(inout) :: buffer
integer(kind=int32), intent(in) :: count
integer(kind=int32), intent(in) :: root
private subroutine comm_bcast_real_dp_array(comm, buffer, count, root)
Broadcasts double precision array from root process to all processes in communicator
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(inout) :: buffer(:)
integer(kind=int32), intent(in) :: count
integer(kind=int32), intent(in) :: root
private subroutine comm_bcast_real_sp(comm, buffer, count, root)
Broadcasts single-precision data from root process to all processes in communicator
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(inout) :: buffer
integer(kind=int32), intent(in) :: count
integer(kind=int32), intent(in) :: root
private subroutine comm_bcast_real_sp_array(comm, buffer, count, root)
Broadcasts single-precision array from root process to all processes in communicator
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(inout) :: buffer(:)
integer(kind=int32), intent(in) :: count
integer(kind=int32), intent(in) :: root
Call graph
bcast calls comm_bcast_integer64, comm_bcast_integer, comm_bcast_real_dp_array, comm_bcast_real_dp, comm_bcast_real_sp_array, comm_bcast_real_sp
comm_bcast_integer64 calls mpi_bcast
comm_bcast_integer calls mpi_bcast
comm_bcast_real_dp_array calls mpi_bcast
comm_bcast_real_dp calls mpi_bcast
comm_bcast_real_sp_array calls mpi_bcast
comm_bcast_real_sp calls mpi_bcast