comm_null – PIC-MPI
comm_null Interface
3 statements
Source File
public interface comm_null
Calls
Called by
Module Procedures
private function create_null_comm() result(comm)
Creates an invalid/null communicator object that can be used for initialization or to represent absence of a communicator.
Arguments
None
Return Value type(comm_t)
Call graph
comm_null calls create_null_comm
comm_discard_leader calls comm_null, comm_split_by_color
comm_discard_to calls comm_null, comm_split_by_color
comm_duplicate calls comm_null
comm_split_by_color calls comm_null
comm_split_shared calls comm_null
darrays_init calls comm_duplicate
darrays_set_comm calls comm_duplicate
dlb_init calls comm_duplicate