comm_world – PIC-MPI
comm_world Interface
3 statements
Source File
public interface comm_world
Calls
Module Procedures
private function create_world_comm() result(comm)
Arguments
None
Return Value type(comm_t)
Call graph
comm_world calls create_world_comm
create_world_comm calls mpi_comm_dup, create_comm_from_mpi
create_comm_from_mpi calls mpi_comm_rank, mpi_comm_size