darray_get – PIC-MPI
darray_get Interface
6 statements
Source File
public interface darray_get
Calls
Module Procedures
private subroutine darray_get_dp(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
real(kind=dp), intent(out) :: buffer(*)
private subroutine darray_get_sp(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
real(kind=sp), intent(out) :: buffer(*)
private subroutine darray_get_i32(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
integer(kind=int32), intent(out) :: buffer(*)
private subroutine darray_get_i64(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
integer(kind=int64), intent(out) :: buffer(*)
Call graph
darray_get calls darray_get_dp, darray_get_i32, darray_get_i64, darray_get_sp
darray_get_dp calls waitall, get_local_offset, get_owner, win_flush_all, win_lock_all, win_rget_dp, win_unlock_all
darray_get_i32 calls waitall, get_local_offset, get_owner, win_flush_all, win_lock_all, win_rget_i32, win_unlock_all
darray_get_i64 calls waitall, get_local_offset, get_owner, win_flush_all, win_lock_all, win_rget_i64, win_unlock_all
darray_get_sp calls waitall, get_local_offset, get_owner, win_flush_all, win_lock_all, win_rget_sp, win_unlock_all
waitall calls request_waitall
get_local_offset calls get_owner, calculate_distribution
win_flush_all calls mpi_win_flush_all
win_lock_all calls mpi_win_lock_all
win_rget_dp calls mpi_rget
win_rget_i32 calls mpi_rget
win_rget_i64 calls mpi_rget
win_rget_sp calls mpi_rget
win_unlock_all calls mpi_win_unlock_all
request_waitall calls mpi_waitall