darray_create – PIC-MPI
darray_create Interface
6 statements
Source File
public interface darray_create
Calls
Module Procedures
private subroutine darray_create_dp(nrows, ncols, handle, init_val)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: nrows
integer(kind=int32), intent(in) :: ncols
integer(kind=int32), intent(out) :: handle
real(kind=dp), intent(in) :: init_val
private subroutine darray_create_sp(nrows, ncols, handle, init_val)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: nrows
integer(kind=int32), intent(in) :: ncols
integer(kind=int32), intent(out) :: handle
real(kind=sp), intent(in) :: init_val
private subroutine darray_create_i32(nrows, ncols, handle, init_val)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: nrows
integer(kind=int32), intent(in) :: ncols
integer(kind=int32), intent(out) :: handle
integer(kind=int32), intent(in) :: init_val
private subroutine darray_create_i64(nrows, ncols, handle, init_val)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: nrows
integer(kind=int32), intent(in) :: ncols
integer(kind=int32), intent(out) :: handle
integer(kind=int64), intent(in) :: init_val
Call graph
darray_create calls darray_create_dp, darray_create_i32, darray_create_i64, darray_create_sp
darray_create_dp calls win_allocate, calculate_distribution, comm_barrier, find_free_slot
darray_create_i32 calls win_allocate, calculate_distribution, comm_barrier, find_free_slot
darray_create_i64 calls win_allocate, calculate_distribution, comm_barrier, find_free_slot
darray_create_sp calls win_allocate, calculate_distribution, comm_barrier, find_free_slot
win_allocate calls create_win_allocate_dp_1d, create_win_allocate_dp_2d, create_win_allocate_i32_1d, create_win_allocate_i64_1d, create_win_allocate_sp_1d
comm_barrier calls mpi_barrier
create_win_allocate_dp_1d calls mpi_win_allocate, comm_get
create_win_allocate_dp_2d calls mpi_win_allocate, comm_get
create_win_allocate_i32_1d calls mpi_win_allocate, comm_get
create_win_allocate_i64_1d calls mpi_win_allocate, comm_get
create_win_allocate_sp_1d calls mpi_win_allocate, comm_get