darray_acc – PIC-MPI
darray_acc Interface
6 statements
Source File
public interface darray_acc
Calls
Module Procedures
private subroutine darray_acc_dp(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
real(kind=dp), intent(in) :: buffer(*)
private subroutine darray_acc_sp(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
real(kind=sp), intent(in) :: buffer(*)
private subroutine darray_acc_i32(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
integer(kind=int32), intent(in) :: buffer(*)
private subroutine darray_acc_i64(handle, ilo, ihi, jlo, jhi, buffer)
Arguments
Type Intent Optional Attributes Name
integer(kind=int32), intent(in) :: handle
integer(kind=int32), intent(in) :: ilo
integer(kind=int32), intent(in) :: ihi
integer(kind=int32), intent(in) :: jlo
integer(kind=int32), intent(in) :: jhi
integer(kind=int64), intent(in) :: buffer(*)
Call graph
darray_acc calls darray_acc_dp, darray_acc_i32, darray_acc_i64, darray_acc_sp
darray_acc_dp calls get_local_offset, get_owner, win_accumulate_dp
darray_acc_i32 calls get_local_offset, get_owner, win_accumulate_i32
darray_acc_i64 calls get_local_offset, get_owner, win_accumulate_i64
darray_acc_sp calls get_local_offset, get_owner, win_accumulate_sp
get_local_offset calls get_owner, calculate_distribution
win_accumulate_dp calls mpi_accumulate
win_accumulate_i32 calls mpi_accumulate
win_accumulate_i64 calls mpi_accumulate
win_accumulate_sp calls mpi_accumulate