irecv – PIC-MPI
irecv Interface
13 statements
Source File
public interface irecv
Calls
Module Procedures
private subroutine comm_irecv_integer(comm, data, source, tag, request)
Initiates a non-blocking receive operation. The request must be waited on using wait() or test() before the buffer can be used.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_integer_array(comm, data, source, tag, request)
Initiates a non-blocking receive operation. The request must be waited on using wait() or test() before the buffer can be used.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(out) :: data(:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_integer64(comm, data, source, tag, request)
Initiates a non-blocking receive operation. The request must be waited on using wait() or test() before the buffer can be used.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_integer64_array(comm, data, source, tag, request)
Initiates a non-blocking receive operation. The request must be waited on using wait() or test() before the buffer can be used.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(out) :: data(:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_real_dp(comm, data, source, tag, request)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_real_dp_array(comm, data, source, tag, request)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(out) :: data(:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_real_dp_array_2d(comm, data, source, tag, request)
Non-blocking receive of a 2D allocatable double precision real array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(inout), allocatable :: data(:,:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_real_sp(comm, data, source, tag, request)
Non-blocking receive of a single single-precision real
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_real_sp_array(comm, data, source, tag, request)
Non-blocking receive of a single-precision real array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(out) :: data(:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_real_sp_array_2d(comm, data, source, tag, request)
Non-blocking receive of a 2D allocatable single-precision real array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(inout), allocatable :: data(:,:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_irecv_logical(comm, data, source, tag, request)
Non-blocking receive of a logical value
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
logical, intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
Call graph
irecv calls comm_irecv_integer64_array, comm_irecv_integer64, comm_irecv_integer_array, comm_irecv_integer, comm_irecv_logical, comm_irecv_real_dp_array_2d, comm_irecv_real_dp_array, comm_irecv_real_dp, comm_irecv_real_sp_array_2d, comm_irecv_real_sp_array, comm_irecv_real_sp
comm_irecv_integer64_array calls mpi_irecv
comm_irecv_integer64 calls mpi_irecv
comm_irecv_integer_array calls mpi_irecv
comm_irecv_integer calls mpi_irecv
comm_irecv_logical calls mpi_irecv
comm_irecv_real_dp_array_2d calls mpi_irecv, mpi_recv
comm_irecv_real_dp_array calls mpi_irecv
comm_irecv_real_dp calls mpi_irecv
comm_irecv_real_sp_array_2d calls mpi_irecv, mpi_recv
comm_irecv_real_sp_array calls mpi_irecv
comm_irecv_real_sp calls mpi_irecv