isend – PIC-MPI
isend Interface
13 statements
Source File
public interface isend
Calls
Module Procedures
private subroutine comm_isend_integer(comm, data, dest, tag, request)
Initiates a non-blocking send operation. The request must be waited on using wait() or test() before the buffer can be reused.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_integer_array(comm, data, dest, tag, request)
Initiates a non-blocking send operation. The request must be waited on using wait() or test() before the buffer can be reused.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(in) :: data(:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_integer64(comm, data, dest, tag, request)
Initiates a non-blocking send operation. The request must be waited on using wait() or test() before the buffer can be reused.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_integer64_array(comm, data, dest, tag, request)
Initiates a non-blocking send operation. The request must be waited on using wait() or test() before the buffer can be reused.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(in) :: data(:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_real_dp(comm, data, dest, tag, request)
Initiates a non-blocking send operation. The request must be waited on using wait() or test() before the buffer can be reused.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_real_dp_array(comm, data, dest, tag, request)
Initiates a non-blocking send operation. The request must be waited on using wait() or test() before the buffer can be reused.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(in) :: data(:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_real_dp_array_2d(comm, data, dest, tag, request)
Non-blocking send of a 2D double precision real array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(in) :: data(:,:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_real_sp(comm, data, dest, tag, request)
Non-blocking send of a single single-precision real
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_real_sp_array(comm, data, dest, tag, request)
Non-blocking send of a single-precision real array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(in) :: data(:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_real_sp_array_2d(comm, data, dest, tag, request)
Non-blocking send of a 2D single-precision real array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(in) :: data(:,:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
private subroutine comm_isend_logical(comm, data, dest, tag, request)
Non-blocking send of a logical value
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
logical, intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
type(request_t), intent(out) :: request
Call graph
isend calls comm_isend_integer64_array, comm_isend_integer64, comm_isend_integer_array, comm_isend_integer, comm_isend_logical, comm_isend_real_dp_array_2d, comm_isend_real_dp_array, comm_isend_real_dp, comm_isend_real_sp_array_2d, comm_isend_real_sp_array, comm_isend_real_sp
comm_isend_integer64_array calls mpi_isend
comm_isend_integer64 calls mpi_isend
comm_isend_integer_array calls mpi_isend
comm_isend_integer calls mpi_isend
comm_isend_logical calls mpi_isend
comm_isend_real_dp_array_2d calls mpi_isend, mpi_send
comm_isend_real_dp_array calls mpi_isend
comm_isend_real_dp calls mpi_isend
comm_isend_real_sp_array_2d calls mpi_isend, mpi_send
comm_isend_real_sp_array calls mpi_isend
comm_isend_real_sp calls mpi_isend