recv – PIC-MPI
recv Interface
13 statements
Source File
public interface recv
Calls
Module Procedures
private subroutine comm_recv_integer(comm, data, source, tag, status)
Blocking receive of an integer from specified source. Use MPI_ANY_SOURCE or MPI_ANY_TAG for wildcards.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out), optional :: status
private subroutine comm_recv_integer_array(comm, data, source, tag, status)
Blocking receive of an integer array from specified source.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(out), allocatable :: data(:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out) :: status
private subroutine comm_recv_integer64(comm, data, source, tag, status)
Blocking receive of an integer64 from specified source. Use MPI_ANY_SOURCE or MPI_ANY_TAG for wildcards.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out), optional :: status
private subroutine comm_recv_integer64_array(comm, data, source, tag, status)
Blocking receive of an integer64 array from specified source. Array is automatically allocated to the correct size.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(out), allocatable :: data(:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out) :: status
private subroutine comm_recv_real_dp(comm, data, source, tag, status)
Blocking receive of a single double precision real from specified source.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out), optional :: status
private subroutine comm_recv_real_dp_array(comm, data, source, tag, status)
Blocking receive of a double precision real array from specified source.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(out), allocatable :: data(:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status) :: status
private subroutine comm_recv_real_dp_array_2d(comm, data, source, tag, status)
Blocking receive of a 2D allocatable double precision real array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(inout), allocatable :: data(:,:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out) :: status
private subroutine comm_recv_real_sp(comm, data, source, tag, status)
Blocking receive of a single single-precision real from specified source.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out), optional :: status
private subroutine comm_recv_real_sp_array(comm, data, source, tag, status)
Blocking receive of a single-precision real array from specified source.
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(out), allocatable :: data(:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status) :: status
private subroutine comm_recv_real_sp_array_2d(comm, data, source, tag, status)
Blocking receive of a 2D allocatable single-precision real array
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(inout), allocatable :: data(:,:)
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out) :: status
private subroutine comm_recv_logical(comm, data, source, tag, status)
Blocking receive of a logical value from specified source
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
logical, intent(out) :: data
integer(kind=int32), intent(in) :: source
integer(kind=int32), intent(in) :: tag
type(MPI_Status), intent(out), optional :: status
Call graph
recv calls comm_recv_integer64_array, comm_recv_integer64, comm_recv_integer_array, comm_recv_integer, comm_recv_logical, comm_recv_real_dp_array_2d, comm_recv_real_dp_array, comm_recv_real_dp, comm_recv_real_sp_array_2d, comm_recv_real_sp_array, comm_recv_real_sp
comm_recv_integer64_array calls mpi_get_count, mpi_probe, mpi_recv
comm_recv_integer64 calls mpi_recv
comm_recv_integer_array calls mpi_get_count, mpi_probe, mpi_recv
comm_recv_integer calls mpi_recv
comm_recv_logical calls mpi_recv
comm_recv_real_dp_array_2d calls mpi_recv
comm_recv_real_dp_array calls mpi_get_count, mpi_probe, mpi_recv
comm_recv_real_dp calls mpi_recv
comm_recv_real_sp_array_2d calls mpi_recv
comm_recv_real_sp_array calls mpi_get_count, mpi_probe, mpi_recv
comm_recv_real_sp calls mpi_recv