send – PIC-MPI
send Interface
13 statements
Source File
public interface send
Calls
Module Procedures
private subroutine comm_send_integer(comm, data, dest, tag)
Blocking send of an integer to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_integer_array(comm, data, dest, tag)
Blocking send of an integer array to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int32), intent(in) :: data(:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_integer64(comm, data, dest, tag)
Blocking send of an integer64 to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_integer64_array(comm, data, dest, tag)
Blocking send of an integer64 array to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer(kind=int64), intent(in) :: data(:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_real_dp(comm, data, dest, tag)
Blocking send of a single double precision real to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_real_dp_array(comm, data, dest, tag)
Blocking send of a double precision real array to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(in) :: data(:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_real_dp_array_2d(comm, data, dest, tag)
Blocking send of a 2D double precision real array to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=dp), intent(in) :: data(:,:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_real_sp(comm, data, dest, tag)
Blocking send of a single single-precision real to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_real_sp_array(comm, data, dest, tag)
Blocking send of a single-precision real array to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(in) :: data(:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_real_sp_array_2d(comm, data, dest, tag)
Blocking send of a 2D single-precision real array to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
real(kind=sp), intent(in) :: data(:,:)
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
private subroutine comm_send_logical(comm, data, dest, tag)
Blocking send of a logical value to specified destination
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
logical, intent(in) :: data
integer(kind=int32), intent(in) :: dest
integer(kind=int32), intent(in) :: tag
Call graph
send calls comm_send_integer64_array, comm_send_integer64, comm_send_integer_array, comm_send_integer, comm_send_logical, comm_send_real_dp_array_2d, comm_send_real_dp_array, comm_send_real_dp, comm_send_real_sp_array_2d, comm_send_real_sp_array, comm_send_real_sp
comm_send_integer64_array calls mpi_send
comm_send_integer64 calls mpi_send
comm_send_integer_array calls mpi_send
comm_send_integer calls mpi_send
comm_send_logical calls mpi_send
comm_send_real_dp_array_2d calls mpi_send
comm_send_real_dp_array calls mpi_send
comm_send_real_dp calls mpi_send
comm_send_real_sp_array_2d calls mpi_send
comm_send_real_sp_array calls mpi_send
comm_send_real_sp calls mpi_send