waitall – PIC-MPI
waitall Interface
3 statements
Source File
public interface waitall
Calls
Called by
Module Procedures
private subroutine request_waitall(requests, statuses)
Blocks until all operations in the request array complete. All requests are freed after completion.
Arguments
Type Intent Optional Attributes Name
type(request_t), intent(inout) :: requests(:)
type(MPI_Status), intent(out), optional :: statuses(:)
Call graph
waitall calls request_waitall
request_waitall calls mpi_waitall
darray_get_dp calls waitall
darray_get_i32 calls waitall
darray_get_i64 calls waitall
darray_get_sp calls waitall
darray_put_dp calls waitall
darray_put_i32 calls waitall
darray_put_i64 calls waitall
darray_put_sp calls waitall
darray_get calls darray_get_dp, darray_get_i32, darray_get_i64, darray_get_sp
darray_put calls darray_put_dp, darray_put_i32, darray_put_i64, darray_put_sp