win_allocate – PIC-MPI
win_allocate Interface
7 statements
Source File
public interface win_allocate
Calls
Module Procedures
private subroutine create_win_allocate_dp_1d(comm, length, baseptr, win)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer, intent(in) :: length
real(kind=dp), intent(out), pointer :: baseptr(:)
type(win_t), intent(out) :: win
private subroutine create_win_allocate_dp_2d(comm, dim1, dim2, baseptr, win)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer, intent(in) :: dim1
integer, intent(in) :: dim2
real(kind=dp), intent(out), pointer :: baseptr(:,:)
type(win_t), intent(out) :: win
private subroutine create_win_allocate_sp_1d(comm, length, baseptr, win)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer, intent(in) :: length
real(kind=sp), intent(out), pointer :: baseptr(:)
type(win_t), intent(out) :: win
private subroutine create_win_allocate_i32_1d(comm, length, baseptr, win)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer, intent(in) :: length
integer(kind=int32), intent(out), pointer :: baseptr(:)
type(win_t), intent(out) :: win
private subroutine create_win_allocate_i64_1d(comm, length, baseptr, win)
Arguments
Type Intent Optional Attributes Name
type(comm_t), intent(in) :: comm
integer, intent(in) :: length
integer(kind=int64), intent(out), pointer :: baseptr(:)
type(win_t), intent(out) :: win
Call graph
win_allocate calls create_win_allocate_dp_1d, create_win_allocate_dp_2d, create_win_allocate_i32_1d, create_win_allocate_i64_1d, create_win_allocate_sp_1d
create_win_allocate_dp_1d calls mpi_win_allocate, comm_get
create_win_allocate_dp_2d calls mpi_win_allocate, comm_get
create_win_allocate_i32_1d calls mpi_win_allocate, comm_get
create_win_allocate_i64_1d calls mpi_win_allocate, comm_get
create_win_allocate_sp_1d calls mpi_win_allocate, comm_get